near/near-cli-rs

Cargo.lock, Cargo.toml, src/main.rs
Usage from bash:
```
$ export PATH="$PATH:$(pwd)/target/debug/"
$ near-cli generate-shell-completions bash > /tmp/near-cli-bash-completion
$ source /tmp/near-cli-bash-completion
$ near-cli <TAB><TAB>
construct-transaction       -h                          help                        -V
generate-shell-completions  --help                      utils                       --version
$ near-cli cons<TAB>
$ near-cli construct-transaction
...
```
=> feat: Added a `generate-shell-completions` subcommand that produce static tab-completion scripts for bash, zsh, fish, powershell, and elvish

src/commands/add_command/access_key/public_key_mode/add_access_key/function_call_type/mod.rs, src/commands/add_command/contract_code/contract/initialize_mode/call_function_type/mod.rs, src/commands/add_command/stake_proposal/transfer_near_tokens_type/mod.rs, src/commands/add_command/sub_account/deposit/mod.rs, src/commands/construct_transaction_command/transaction_actions/add_access_key_type/function_call_type/mod.rs, src/commands/construct_transaction_command/transaction_actions/call_function_type/mod.rs, src/commands/construct_transaction_command/transaction_actions/stake_near_tokens_type/mod.rs, src/commands/construct_transaction_command/transaction_actions/transfer_near_tokens_type/mod.rs, src/commands/execute_command/change_method/call_function_type/mod.rs, src/commands/transfer_command/transfer_near_tokens_type/mod.rs, src/commands/view_command/view_account/sender/mod.rs, src/common.rs
Before:
After:
I also refactored `NearBalance`, and had to replace all the usages.
=> feat(view-account): switched `view account-summary` command from displaying raw data to human-readable format

src/commands/execute_command/change_method/call_function_type/mod.rs
The maximum gas is limited to 300Tgas, but the burn gas limit is restricted to 200Tgas.
=> Bump gas for a function call to 300Tgas

Cargo.lock, Cargo.toml
https://github.com/near/nearcore/pull/4651 was merged, we can revert to nearcore master.
=> chore(deps): revert nearcore to upstream repo

src/common.rs
The dot there is redundant and it doesn't allow to copy tx hash by double-clicking on it. It catches the dot as well.
=> Remove dot in tx ID message

src/commands/view_command/view_account/block_id/block_id_hash/mod.rs, src/commands/view_command/view_account/block_id/block_id_height/mod.rs, src/commands/view_command/view_account/block_id/mod.rs, src/common.rs
Deduplicates functions like `display_account_info` and `display_access_key_list`, and puts them into `common.rs`.
This is just one part of the cleanup process, and there will be more after this one. Don't want to snowball all of these into one giant PR, since that wouldn't be good for anyone looking at it, nor would it increase the chance of it being looked at. So let's go with integrating cleanups often
=> refactor: Dedup display functions for view commands

extensions/README.md
Followup for this comment: https://github.com/near/near-cli-rs/pull/66#discussion_r718750206
I will create a separate discussion for `near-{}` vs `near-cli-{}`.
=> docs: extensions doc minor fix

src/main.rs
Not sure if the best solution to #54. After requiring the installation of the program maybe replace it with `CARGO_PKG_NAME`.
Also do we need `unwrap_or` here, for cases, when argc==0? I think that most users will use this program normally.
=> feat: Use currently running binary name in "Your console command" output

src/commands/add_command/contract_code/contract/mod.rs, src/commands/construct_transaction_command/transaction_actions/add_contract_code_type/mod.rs
Fixes #55.
If you try to deploy a contract and enter a wrong path, the error appears :
```
Error: 
0: Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location:
src/commands/add_command/contract_code/contract/mod.rs:30
```
I propose to change it to:
```
Error: 
0: Failed to open or read the file: "~/projects/near/contract/res/contract.was".
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location:
src/commands/add_command/contract_code/contract/mod.rs:30
```
=> "Failed to open file" error is more understandable

src/commands/add_command/access_key/operation_mode/mod.rs, src/commands/add_command/contract_code/contract/initialize_mode/call_function_type/mod.rs, src/commands/add_command/contract_code/contract/mod.rs, src/commands/construct_transaction_command/transaction_actions/add_contract_code_type/mod.rs, src/commands/construct_transaction_command/transaction_actions/call_function_type/mod.rs, src/commands/execute_command/change_method/call_function_type/mod.rs, src/commands/execute_command/mod.rs, src/commands/execute_command/view_method/block_id/mod.rs, src/commands/utils_command/mod.rs, src/commands/utils_command/sign_transaction_subcommand_with_secret_key/mod.rs, src/commands/view_command/view_account/block_id/mod.rs, src/commands/view_command/view_contract_code/block_id/mod.rs, src/commands/view_command/view_contract_state/block_id/mod.rs, src/commands/view_command/view_transaction_status/signer/mod.rs, src/common.rs
fixes some basic spelling mistakes (note, I'm not a native speaker so this may not be the most correct stuff)
improves #15
=> improve spelling

src/commands/execute_command/view_method/block_id/block_id_hash/mod.rs, src/commands/execute_command/view_method/block_id/block_id_height/mod.rs, src/commands/execute_command/view_method/block_id/mod.rs
To resolve https://github.com/near/near-cli-rs/issues/104, I vote for defaulting to `null` when the server returns an empty byte array for a view function call.
Note: This doesn't change the behavior for functions that return results.
```console
Your console command:
./near-cli execute view-method network testnet contract hello_sat.testnet call hello {} at-final-block
Error:
0: serde json: Error("EOF while parsing a value", line: 1, column: 0)
Location:
src/commands/execute_command/view_method/block_id/mod.rs:101
```
```console
--------------
null
Your console command:
target/debug/near-cli execute view-method network testnet contract hello_sat.testnet call hello {} at-final-block
```
=> fix: query method reports null on empty result

docs/NEW_NEAR_CLI_INTERFACE.md
Instead of expanding the list of various account creation strategies, I decided to nest them.
=> docs: Restructured the create-account command to nest sponsored / self-funded / non-funded [implicit] account

docs/NEW_NEAR_CLI_INTERFACE.md
Currently, there are basically four ways to "add accounts":
* Import it from the web wallet
* Create a named account by sending a transaction signed by some existing account
* Create a new implicit account (and later fund it from somewhere else)
* Manually add a new file to `~/.near-credentials/*/` keychain
While it is not required to add an account before signing a transaction since we allow signing transactions with a plain-text private key (and I will create a new proposal to enable signing by providing a seed phrase), it is far more convenient and secure if one uses macOS keychain to access the account than pasting seed-phrase or private key over and over again (not to mention that it is not convenient to do).
All these import-account commands will need to have the account id, but if …
=> [Proposal] Design proposal to extend import-account command to import by seed-phrase or private-key

docs/NEW_NEAR_CLI_INTERFACE.md
Currently, we allow using a plain-text private key, but there are occasions where it would be handy to use seed-phrase (usually these are one-off operations and #138 should address other use-cases where an account needs to be used regularly)
P.S. `macos-keychain` is already supported, so I just reflected that in this doc
=> [Proposal] Extend the list of transaction singing options to be able to use access-key file or plain-text seed-phrase

.github/workflows/release-plz.yml, release-plz.toml
The latest release of release-plz removes the `git_release` github action argument.
I disabled github releases with the config file 👍
=> chore: update release-plz-action to v0.5

CHANGELOG.md, Cargo.lock, Cargo.toml, src/commands/account/mod.rs, src/commands/config/mod.rs, src/commands/contract/mod.rs, src/commands/extensions/mod.rs, src/commands/mod.rs, src/commands/tokens/mod.rs, src/commands/transaction/mod.rs
* `near-cli-rs`: 0.3.2 -> 0.4.0 (⚠️ API breaking changes)
```
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-check/tree/v0.19.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field TransactionContext.prepopulated_transaction in /tmp/.tmpVuodlM/near-cli-rs/src/commands/mod.rs:79
--- failure enum_variant_added: enum variant added on exhaustive enum ---
Description:
A publicly-visible enum without #[non_exhaustive] has a new variant.
ref: …
```
=> chore: release v0.3.3

src/common.rs
This PR resolves https://github.com/near/near-cli-rs/issues/186 by replacing the default unwrap function with a logical alternative and adding a formatted error message for better clarity.
=> fixed issue call function with file args shows wrong log

src/commands/account/delete_key/mod.rs, src/commands/account/delete_key/use_publickeylist_type/mod.rs, src/types/mod.rs, src/types/public_key_list.rs
Fixes : #205 
multi public-key for account delete-key command separated  by `,` .
=> feat: multi public-key for account delete-key command

src/js_command_match/view.rs
=> fix: Add support for no-args view-function calls for legacy JS CLI `view` command

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.6.1 -> 0.6.2 (✓ API compatible changes)
<blockquote>
- Exposed some of the functions to use "manage-profile" in bos-cli-rs ([#249](https://github.com/near/near-cli-rs/pull/249))
- Exposed subcommands related to "deploy" to reuse in cargo-near ([#247](https://github.com/near/near-cli-rs/pull/247))
</blockquote>
</p></details>
---
=> chore: release v0.6.2

src/transaction_signature_options/sign_later/mod.rs
In delegated signing contexts it is useful to see the SHA256 hash of the unsigned transaction when using the `sign-later` transaction signature option.
=> Show hash-to-sign when using the sign_later transaction signature option

Cargo.lock, Cargo.toml, src/commands/mod.rs, src/commands/transaction/mod.rs, src/commands/transaction/print_transaction/mod.rs, src/commands/transaction/print_transaction/signed/mod.rs, src/commands/transaction/print_transaction/unsigned/mod.rs, src/commands/transaction/sign_transaction/mod.rs, src/common.rs, src/transaction_signature_options/sign_with_ledger/mod.rs, src/types/signed_transaction.rs
resolves #33 
verify:
tx [link](https://nearblocks.io/txns/26GbdoRxMxTn4ggyStxTPHjTqciWWMka6H4TRTUrox5g) exactly from flow on screens above
=> feat: ledger blind signing

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.7.2 -> 0.7.3 (✓ API compatible changes)
<blockquote>
- Added support for blind signing with Ledger [requires updated Ledger app that is not yet published] ([#259](https://github.com/near/near-cli-rs/pull/259))
- New command to reconstruct NEAR CLI command from a historical transaction ([#266](https://github.com/near/near-cli-rs/pull/266))
- Addressed all default cargo clippy warnings ([#263](https://github.com/near/near-cli-rs/pull/263))
</blockquote>
</p></details>
---
=> chore: release v0.7.3

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.7.3 -> 0.7.4 (✓ API compatible changes)
<blockquote>
- Removed the need for an additional network selection step if there is only one network connection in the config file ([#272](https://github.com/near/near-cli-rs/pull/272))
- Added the ability to interactively select access keys to remove from the list of public keys ([#269](https://github.com/near/near-cli-rs/pull/269))
- Cleaned up duplicative CI checks and renamed 'master' to 'main' default branch
- Automate publishing near-cli-rs to npmjs for `npx near-cli-rs` to use the latest released binary release by default ([#273](https://github.com/near/near-cli-rs/pull/273))
</blockquote>
</p></details>
---
This PR was generated with …
=> chore: release v0.7.4

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.7.4 -> 0.7.5 (✓ API compatible changes)
<blockquote>
- Improved self-update UX with more details ([#274](https://github.com/near/near-cli-rs/pull/274))
- Display NEAR token amounts precisely ([#278](https://github.com/near/near-cli-rs/pull/278))
- Updated the guide around the usage of system keychain on Linux, Windows, and macOS ([#277](https://github.com/near/near-cli-rs/pull/277))
- Added explicit installation instructions to README.md
</blockquote>
</p></details>
---
=> chore: release v0.7.5

docs/GUIDE.en.md, docs/GUIDE.ru.md, src/commands/transaction/view_status/mod.rs, src/js_command_match/tx_status.rs
=> refactor: Updated transaction status view

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.7.5 -> 0.7.6 (✓ API compatible changes)
<blockquote>
- Removed excessive step during transaction status view to improve UX ([#280](https://github.com/near/near-cli-rs/pull/280))
- Updated reconstruct-transaction command ([#281](https://github.com/near/near-cli-rs/pull/281))
</blockquote>
</p></details>
---
=> chore: release v0.7.6

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.7.6 -> 0.7.7 (✓ API compatible changes)
<blockquote>
- Updated dialog for entering arguments to a function (as-read-only) ([#285](https://github.com/near/near-cli-rs/pull/285))
- Updated binary releases pipeline to use cargo-dist v0.7.2 (previously v0.3.0) ([#289](https://github.com/near/near-cli-rs/pull/289))
- Avoid unnecessary "interactive_clap::FromCli" implementations ([#288](https://github.com/near/near-cli-rs/pull/288))
</blockquote>
</p></details>
---
=> chore: release v0.7.7

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.7.7 -> 0.7.8 (✓ API compatible changes)
<blockquote>
- Updated binary releases pipeline to use cargo-dist v0.9.0 (previously v0.7.2) ([#294](https://github.com/near/near-cli-rs/pull/294))
- Updated send-ft command ([#283](https://github.com/near/near-cli-rs/pull/283))
</blockquote>
</p></details>
---
=> chore: release v0.7.8

src/commands/account/view_account_summary/mod.rs, src/common.rs
=> fix: Added support for viewing account summary on networks without NEAR Social contract

Cargo.lock, Cargo.toml, src/common.rs, src/transaction_signature_options/sign_with_ledger/mod.rs
```bash
`near` CLI has a new update available 0.7.2 →  0.8.1
To update `near` CLI use: near extensions self-update
Error:
0: Error occurred while signing the transaction: APDUExchangeError("Unknown Ledger APDU retcode: 27024")
❯ pcalc 27024
27024                   0x6990                  0y110100110010000
❯ rg 0x6990
workdir/app-near/src/constants.h
37:#define SW_BUFFER_OVERFLOW 0x6990
```
```bash
Error:
0: Error occurred while signing the transaction: APDUExchangeError("Ledger APDU retcode: 0x6990")
```
```bash
Unsigned transaction:
signer_id:    1b11b3b31673033936ad07bddc01f9da27d974811e480fb197c799e23480a489
receiver_id:  1b11b3b31673033936ad07bddc01f9da27d974811e480fb197c799e23480a489
actions:
-- deploy contract DC1KnvBEyPhBzBxCBarMgY9ZN68krg449Dk8AxARU2QN
...
```
```bytes
12288 …
```
=> chore: update `near-ledger` to `0.5.0`

src/transaction_signature_options/display/mod.rs, src/transaction_signature_options/mod.rs, src/transaction_signature_options/save_to_file/mod.rs, src/transaction_signature_options/send/mod.rs, src/transaction_signature_options/sign_later/display.rs, src/transaction_signature_options/sign_later/mod.rs, src/transaction_signature_options/sign_later/save_to_file.rs
=> feat: Added the ability to output a signed transaction (serialized as base64) to a file

src/commands/account/view_account_summary/mod.rs, src/commands/config/add_connection/mod.rs, src/common.rs, src/config.rs
I've noticed that `view account summary` command was taking too much time. The problems lay in scanning through validators to find if the user’s account id belongs to it. Furthermore, `get_validators_stake` function didn't give all available validators, only +-240 out of 450 were scannable. To fix this, I used fastnear API to retrieve validators in one request, if this process fails, then it will switch to the previous strategy
*before*
*after*
=> feat: improved fetching staking pools

Cargo.lock, Cargo.toml, src/commands/account/view_account_summary/mod.rs, src/commands/config/add_connection/mod.rs, src/common.rs, src/config/migrations.rs, src/config/mod.rs, src/transaction_signature_options/send/mod.rs
Displaying a simple transaction fee after transaction execution
This PR closes #320
=> feat: displaying transaction fee 

src/commands/account/delete_key/public_keys_to_delete.rs
=> fix: Fallback to non-auto-suggesting input of the keys to be deleted in interactive mode in offline mode or if there is a connectivity issue

src/commands/account/add_key/access_key_type/mod.rs, src/js_command_match/add_key.rs, src/types/mod.rs, src/types/near_allowance.rs, src/types/near_token.rs
Resolves #341 
_near-cli_ (JS) command with "allowance":
```
near add-key example-acct.testnet GkMNfc92fwM1AmwH1MTjF4b7UZuceamsq96XPkHsQ9vi --allowance 30000000000 --contract-id example-contract.testnet --method-names example_method
```
_near-cli-rs_ command:
```
near account add-key example-acct.testnet grant-function-call-access --allowance '30000000000 NEAR' --receiver-account-id example-contract.testnet --method-names example_method use-manually-provided-public-key GkMNfc92fwM1AmwH1MTjF4b7UZuceamsq96XPkHsQ9vi network-config testnet sign-with-keychain send
```
_near-cli_ (JS) command without "allowance":
```
near add-key example-acct.testnet GkMNfc92fwM1AmwH1MTjF4b7UZuceamsq96XPkHsQ9vi --contract-id example-contract.testnet --method-names example_method
```
_near-cli-rs_ command:
``` …
```
=> fix: Wrong console command for adding Function-Call key with unlimited allowance

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.10.1 -> 0.10.2 (✓ API compatible changes)
<blockquote>
- Wrong console command for adding Function-Call key with unlimited allowance ([#342](https://github.com/near/near-cli-rs/pull/342))
- Fallback to non-auto-suggesting input of the keys to be deleted in interactive mode in offline mode or if there is a connectivity issue ([#338](https://github.com/near/near-cli-rs/pull/338))
</blockquote>
</p></details>
---
=> chore: release v0.10.2

src/commands/account/view_account_summary/mod.rs, src/common.rs
Instead of throwing an error when some insignificant parts of the command fail, we can print a warning message and continue the workflow
This PR closes #343
=> feat: improved error handling

src/common.rs
I found out that certain headless linux systems don't implement keyring. For example on WSL we can`t use keychain because it is not seted up by default. User need to install gnome-keyring with pip3, start D-bust session and unlock keychain. Close https://github.com/near/near-cli-rs/issues/299
=> Give instructions that help to resolve a problem with missing keychain

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.10.2 -> 0.11.0
<blockquote>
- Added loading indicators to wait for the view-account-summary command ([#349](https://github.com/near/near-cli-rs/pull/349))
- Added loading indicators to wait for the create-account (sponsor-by-faucet-service) command ([#339](https://github.com/near/near-cli-rs/pull/339))
- Do not fail view-account-summary command if we could not retrieve access keys list ([#344](https://github.com/near/near-cli-rs/pull/344))
- [**breaking**] upgraded near-dependencies to the 0.23 version ([#350](https://github.com/near/near-cli-rs/pull/350))
- Provide instructions that help to resolve a problem with missing keychain ([#347](https://github.com/near/near-cli-rs/pull/347))
</blockquote>
</p></details> …
=> chore: release v0.11.0

Cargo.lock, Cargo.toml, src/commands/account/add_key/use_manually_provided_seed_phrase/mod.rs, src/commands/account/create_account/fund_myself_create_account/add_key/use_manually_provided_seed_phrase/mod.rs, src/commands/account/create_account/sponsor_by_faucet_service/add_key/use_manually_provided_seed_phrase/mod.rs, src/commands/transaction/construct_transaction/add_action_1/add_action/add_key/use_manually_provided_seed_phrase/mod.rs, src/commands/transaction/construct_transaction/add_action_2/add_action/add_key/use_manually_provided_seed_phrase/mod.rs, src/commands/transaction/construct_transaction/add_action_3/add_action/add_key/use_manually_provided_seed_phrase/mod.rs, src/common.rs, src/transaction_signature_options/sign_with_ledger/mod.rs, src/types/slip10.rs
go from 
<details>
<summary>ed25519-dalek v1.0.1 + ed25519-dalek@2.1.1</summary><p>
```bash
ed25519-dalek v1.0.1
├── ed25519-dalek feature "default"
│   ├── near-cli-rs v0.11.0 (/home/user/Documents/code/rust_work_repos/near/near-cli-rs)
│   │   ├── near-cli-rs feature "default" (command-line)
│   │   ├── near-cli-rs feature "ledger"
│   │   │   └── near-cli-rs feature "default" (command-line)
│   │   ├── near-cli-rs feature "near-ledger"
│   │   │   └── near-cli-rs feature "ledger" (*)
│   │   ├── near-cli-rs feature "self-update"
│   │   │   └── near-cli-rs feature "default" (command-line)
│   │   ├── near-cli-rs feature "self_update"
│   │   │   └── near-cli-rs feature "self-update" (*)
│   │   └── near-cli-rs feature "semver"
│   │       └── near-cli-rs feature "self-update" (*)
│ …
```
=> chore: replace `ed25519-dalek` 1 -> 2 major version

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.11.0 -> 0.11.1
<blockquote>
- Added loading indicators for "contract" group commands  ([#357](https://github.com/near/near-cli-rs/pull/357))
- Added loading indicators for "staking" group commands ([#356](https://github.com/near/near-cli-rs/pull/356))
- Added loading indicators for "tokens" group commands ([#355](https://github.com/near/near-cli-rs/pull/355))
- Added loading indicators for "accounts" group commands ([#352](https://github.com/near/near-cli-rs/pull/352))
- replace `ed25519-dalek` 1 -> 2 major version ([#359](https://github.com/near/near-cli-rs/pull/359))
</blockquote>
</p></details>
---
=> chore: release v0.11.1

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.11.1 -> 0.12.0
<blockquote>
- Cover *all* commands from near-cli JS with the new near-cli-rs suggestions for full compatibility  ([#345](https://github.com/near/near-cli-rs/pull/345))
- Added the ability to select HD Path from the ledger ([#362](https://github.com/near/near-cli-rs/pull/362))
- Added loading indicators for "transaction" group commands and improved the prompt messages  ([#358](https://github.com/near/near-cli-rs/pull/358))
</blockquote>
</p></details>
---
=> chore: release v0.12.0

docs/GUIDE.en.md, docs/GUIDE.ru.md, docs/NEW_NEAR_CLI_INTERFACE.md, src/commands/staking/delegate/mod.rs
avalidator --> validator 
usefull  --> useful
=> chore: fix some typos

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.12.0 -> 0.13.0
<blockquote>
- Automatically exec legacy JS CLI commands for full backward compatibility ([#366](https://github.com/near/near-cli-rs/pull/366))
- Added the ability to use the TEACH-ME mode ([#360](https://github.com/near/near-cli-rs/pull/360))
- Added a new subcommand to edit configuration parameters ([#367](https://github.com/near/near-cli-rs/pull/367))
- Fixed the fallback implementation of fetching active staking pools ([#369](https://github.com/near/near-cli-rs/pull/369))
- Fixed typos in user prompts and the guide ([#372](https://github.com/near/near-cli-rs/pull/372))
</blockquote>
</p></details>
---
=> chore: release v0.13.0

src/commands/contract/call_function/mod.rs
=> fix: Entering the name of the function in interactive mode

src/main.rs
[inspired by this example: https://github.com/near/cargo-near/pull/196](https://github.com/near/cargo-near/pull/196)
=> chore: Disable env section of color_eyre report

src/commands/account/view_account_summary/mod.rs, src/common.rs
=> fix: Left a message that information about the delegated stake could not be obtained, instead of failing the operation completely

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.13.0 -> 0.13.1
<blockquote>
- Require at least one access key to be selected in interactive mode when deleting a key ([#385](https://github.com/near/near-cli-rs/pull/385))
- Handle delegated stake errors gracefully and display a warning message instead of failing the view-account-summary command completely ([#382](https://github.com/near/near-cli-rs/pull/382))
- Entering the name of the function in interactive mode ([#379](https://github.com/near/near-cli-rs/pull/379))
- Fixed a typo in `inspect` output about missing ABI support ([#374](https://github.com/near/near-cli-rs/pull/374))
- updated near-* to 0.24.0, bumped up rust version ([#381](https://github.com/near/near-cli-rs/pull/381))
- Added videos to the README …
=> chore: release v0.14.0

Cargo.lock, Cargo.toml
After a recent upgrade of keyring from 2.x to 3.x, all the features became disabled by default instead of enabled by default, so we have to enable them back again.
@race-of-sloths invite
=> fix: Fixed native operating system keychain support

src/transaction_signature_options/sign_with_legacy_keychain/mod.rs
=> feat: The priority of searching in the legacy keychain for access keys when signing a transaction has been changed

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.14.1 -> 0.14.2
<blockquote>
- Upgraded cargo-dist to 0.21.1 and enabled Linux ARM64 build ([#397](https://github.com/near/near-cli-rs/pull/397))
- Prioritize searching an access key in the signer account subfolder (<credentials-dir>/<network>/<account-id>/*.json) in legacy keychain and then fallback to <credentials-dir>/<network>/<account-id>.json instead of the other way around ([#396](https://github.com/near/near-cli-rs/pull/396))
- Fixed the one-liner curl installation command
</blockquote>
</p></details>
---
=> chore: release v0.14.2

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.14.2 -> 0.14.3
<blockquote>
- Fixed the fallback legacy keychain path ([#398](https://github.com/near/near-cli-rs/pull/398))
</blockquote>
</p></details>
---
=> chore: release v0.14.3

Cargo.lock, Cargo.toml, src/transaction_signature_options/sign_with_keychain/mod.rs, src/transaction_signature_options/sign_with_ledger/mod.rs
Added ledger support for meta transactions 
Fixed offline support for keychain 
=> chore: updated near-* to 0.25.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.14.3 -> 0.15.0
<blockquote>
- UX improvement for signing with Ledger - automatically open a near-app on Ledger device before calling methods ([#403](https://github.com/near/near-cli-rs/pull/403))
- Extended --teach-me mode: async account details fetching RPC methods are also covered now ([#389](https://github.com/near/near-cli-rs/pull/389))
- Updated near-* dependencies to 0.25.0 (matching nearcore 2.1 release) ([#401](https://github.com/near/near-cli-rs/pull/401))
</blockquote>
</p></details>
---
=> chore: release v0.15.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.15.0 -> 0.15.1
<blockquote>
- updates near-* dependencies to 0.26 release ([#405](https://github.com/near/near-cli-rs/pull/405))
</blockquote>
</p></details>
---
=> chore: release v0.15.1

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.15.1 -> 0.16.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] updates near-* dependencies to 0.27 release ([#414](https://github.com/near/near-cli-rs/pull/414))
</blockquote>
</p></details>
---
=> chore: release v0.16.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.16.0 -> 0.16.1 (✓ API compatible changes)
<blockquote>
- Added the ability to save payload for broadcast_tx_commit ([#413](https://github.com/near/near-cli-rs/pull/413))
- Get the final CLI command into the shell history with a small helper setup ([#415](https://github.com/near/near-cli-rs/pull/415))
- Trace configuration for loading wait indicators and --teach-me flag moved to library ([#417](https://github.com/near/near-cli-rs/pull/417))
- add to devtools workflow
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.16.1

README.md, docs/README.en.md
Closes #429
@race-of-sloths include
=> docs: Extended the documentation for building NEAR CLI from the source code

src/commands/account/view_account_summary/mod.rs, src/config/migrations.rs, src/config/mod.rs
Closes: #431 
* Added fast-near for testnet
* Rate limited querying pools to 140 / 30s
Ideally, if Fastnear is stable enough, the user shouldn't be able to hit this limit as we will query information within the pools the user has staked before.
But in case the fastener fails, we would need to query all active pools, which number more than 150.
| Network | FastNear | Non fast near |
| :---:   | :---: | :---: |
| Testnet | < 140 (mostly 0-5) | 563 pools 
| Mainnet | < 140 ( mostly 0-5 ) | State of contract poolv1.near is too large to be viewed |
=> bugfix: handle new rate-limits for querying pools

src/commands/account/create_account/create_implicit_account/use_seed_phrase.rs, src/commands/account/get_public_key/from_keychain/mod.rs, src/commands/account/get_public_key/from_ledger/mod.rs, src/commands/account/get_public_key/from_legacy_keychain/mod.rs, src/commands/account/get_public_key/from_seed_phrase/mod.rs, src/commands/account/get_public_key/mod.rs, src/commands/account/import_account/using_seed_phrase/mod.rs, src/commands/account/mod.rs, src/common.rs, src/transaction_signature_options/sign_with_seed_phrase/mod.rs
=> feat: Added the ability to get a public key for an account

Cargo.lock, Cargo.toml, src/commands/account/add_key/autogenerate_new_keypair/save_keypair_to_keychain/mod.rs, src/commands/account/create_account/fund_myself_create_account/add_key/autogenerate_new_keypair/mod.rs, src/commands/account/create_account/sponsor_by_faucet_service/add_key/autogenerate_new_keypair/mod.rs, src/commands/account/import_account/mod.rs, src/common.rs
=> fix: Refactoring the storage of the access key to the keychain

src/commands/transaction/reconstruct_transaction/mod.rs, src/lib.rs, src/main.rs
Improves #437 
@race-of-sloths include
=> feat: A new `--quiet` flag to suppress noisy output in scripting scenarios

src/commands/tokens/send_ft/amount_ft.rs
[NEP-141](https://github.com/near/NEPs/blob/master/neps/nep-0141.md) specifies the interface for fungible tokens.
The `ft_transfer` method has three parameters: `receiver_id`, `amount` and `memo`. `memo` is an optional parameter.
This PR allows users to introduce a memo when using sending fungable tokens using the cli.
The new parameter is optional and its skiped if no data is introduced.
You can see an example of a tx using the new parameter [here](https://testnet.nearblocks.io/txns/92zbxHnaPwJYZpvjvmKzKEdrM6dr9x6QMsxi2msQqDrj#execution#Cak7EmpqpSUv24sT6o4jFGTj1mvWgJt1u4xtxZys8s7B)
=> feat: let users specify a memo when sending ft

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.18.0 -> 0.19.0 (⚠ API breaking changes)
```text
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.39.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field GlobalContext.verbosity in /tmp/.tmpqoEbVp/near-cli-rs/src/lib.rs:19
--- failure function_missing: pub fn removed or renamed ---
Description:
A publicly-visible function cannot be imported by its prior path. A `pub use` may have been removed, or the function itself may have been renamed …
```
=> chore: release v0.19.0

src/transaction_signature_options/sign_with_private_key/mod.rs
Resolves #467 
This fixed the command:
```
near tokens \
fro_volod.testnet \
send-near volodymyr.testnet 0.1NEAR \
network-config testnet \
sign-with-plaintext-private-key --signer-public-key ed25519:abc --signer-private-key ed25519:def \
send
```
to
```
near tokens \
fro_volod.testnet \
send-near volodymyr.testnet 0.1NEAR \
network-config testnet \
sign-with-plaintext-private-key ed25519:def \
send
```
or
```
near tokens \
fro_volod.testnet \
send-near volodymyr.testnet 0.1NEAR \
network-config testnet \
sign-with-plaintext-private-key ed25519:def --nonce 52060514001752 --block-hash BShiHLVzKwzuYLCRjomWngTtNXanhzsgECcpwmqNsqN3 \
send
```
=> fix: Fixed signing transactions with a plaintext private key

src/commands/tokens/send_ft/amount_ft.rs
Resolves #472 
This fixed the generated command:
```
Here is your console command if you need to script it or re-run:
near tokens slimedragon.near send-ft spear-1565.meme-cooking.near slimedragon.near '1 spear' memo network-config mainnet sign-with-keychain send
```
to:
```
Here is your console command if you need to script it or re-run:
near tokens slimedragon.near send-ft spear-1565.meme-cooking.near slimedragon.near '1 spear' memo '' network-config mainnet sign-with-keychain send
```
=> fix: Fixed cli command `near tokens send-ft` without `memo`

src/commands/contract/download_wasm/mod.rs, src/commands/contract/mod.rs, src/commands/transaction/reconstruct_transaction/mod.rs
The RPC stopped providing the code at some point and started to provide only a hash of the contract. This resolves the issue and loads the code manually
=> bugfix: fixed reconstruction of transaction from contract deploy

src/commands/transaction/reconstruct_transaction/mod.rs
Should be restored after https://github.com/near/nearcore/issues/13531 is implemented
=> bugfix: removed unsupported reconstruction for DeployGlobalContract

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.19.0 -> 0.20.0 (⚠ API breaking changes)
```text
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.41.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field CliContract.deploy_mode in /tmp/.tmpg27DR7/near-cli-rs/src/commands/contract/deploy/mod.rs:6
--- failure derive_trait_impl_removed: built-in derived trait no longer implemented ---
Description:
A public type has stopped deriving one or more traits. This can break downstream code that …
```
=> chore: release v0.20.0

docs/SHELL_HISTORY_INTEGRATION.md, src/common.rs
This pull requests closes #479 
Resolves the problem with zsh and Fish shell scripts, not being able to write escaped characters properly into history
=> chore: fixed shell configuration for command history

src/config/mod.rs
This pr closes #452 adding several RPCs for mainnet and testnet:
- FASTNEAR
- Lava
- dRPC
=> chore: added more RPCs to config generation

Cargo.lock, src/common.rs
This should not have been needed, but due to a bug on nearcore side, we have to handle the "Started" status gracefully: https://github.com/near/nearcore/issues/13872
=> feat: Updated transaction status handler (Started, NotStarted)

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.21.0 -> 0.22.0 (⚠ API breaking changes)
```text
--- failure enum_no_repr_variant_discriminant_changed: enum variant had its discriminant change value ---
Description:
The enum's variant had its discriminant value change. This breaks downstream code that used its value via a numeric cast like `as isize`.
ref: https://doc.rust-lang.org/reference/items/enumerations.html#assigning-discriminant-values
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.41.0/src/lints/enum_no_repr_variant_discriminant_changed.ron
Failed in:
variant TopLevelCommandDiscriminants::Config 5 -> 6 in /tmp/.tmphokuMN/near-cli-rs/src/commands/mod.rs:50
variant TopLevelCommandDiscriminants::Extensions 6 -> 7 in /tmp/.tmphokuMN/near-cli-rs/src/commands/mod.rs:54
variant …
```
=> chore: release v0.22.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.22.0 -> 0.22.1 (✓ API compatible changes)
<blockquote>
- update near-* dependencies to 0.31 release ([#514](https://github.com/near/near-cli-rs/pull/514))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.22.1

CHANGELOG.md, Cargo.lock, Cargo.toml
* `near-cli-rs`: 0.22.1 -> 0.22.2 (✓ API compatible changes)
<blockquote>
- Fixed the inspection command for the global contract on the account. ([#513](https://github.com/near/near-cli-rs/pull/513))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.22.2
