- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
> release: version 0.1.14

- Cargo.lock
- Cargo.toml
- src/commands/add_command/contract_code/contract/mod.rs
- src/commands/construct_transaction_command/transaction_actions/add_contract_code_type/mod.rs
- src/commands/view_command/view_contract_code/contract/download_mode/download_contract/mod.rs
Improving user experience on interactive mode, by expanding the path. #90
> feat: Expand ~ in path provided in interactive mode

- Cargo.lock
- Cargo.toml
- src/commands/account/add_key/access_key_type/mod.rs
- src/commands/account/create_account/create_implicit_account/mod.rs
- src/commands/account/create_account/fund_myself_create_account/mod.rs
- src/commands/account/create_account/fund_myself_create_account/sign_as/mod.rs
- src/commands/account/import_account/mod.rs
- src/commands/config/add_connection/mod.rs
- src/commands/contract/call_function/as_transaction/mod.rs
- src/commands/contract/call_function/call_function_args_type/mod.rs
- src/commands/contract/deploy/initialize_mode/call_function_type/mod.rs
- src/commands/contract/download_wasm/mod.rs
- src/commands/tokens/send_ft/mod.rs
- src/commands/tokens/send_near/mod.rs
- src/commands/tokens/send_nft/mod.rs
- src/commands/transaction/construct_transaction/add_access_key/access_key_type/mod.rs
- src/commands/transaction/construct_transaction/call_function/mod.rs
- src/commands/transaction/construct_transaction/deploy_contract/initialize_mode/call_function_type/mod.rs
- src/commands/transaction/construct_transaction/transfer_tokens/mod.rs
- src/common.rs
- src/transaction_signature_options/mod.rs
- src/transaction_signature_options/sign_with_ledger/mod.rs
> Changed library "dialoguer" to "inquire"

- src/commands/account/import_account/mod.rs
- src/commands/account/import_account/using_private_key/mod.rs
- src/commands/account/import_account/using_seed_phrase/mod.rs
- src/common.rs
- src/transaction_signature_options/mod.rs
- src/transaction_signature_options/sign_with_access_key_file/mod.rs
- src/transaction_signature_options/sign_with_keychain/mod.rs
- src/transaction_signature_options/sign_with_macos_keychain/mod.rs
- src/transaction_signature_options/sign_with_seed_phrase/mod.rs
> Added the possibility to sign a transaction using a seed phrase or an account access key file

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/transaction_signature_options/sign_with_seed_phrase/mod.rs
> Exiting CLI with Ctrl+C

- docs/GUIDE.en.md
- docs/GUIDE.ru.md
- src/main.rs
> Added description for readme

- src/common.rs
- src/js_command_match/add_key.rs
- src/js_command_match/call.rs
- src/js_command_match/clean.rs
- src/js_command_match/create_account.rs
- src/js_command_match/delete.rs
- src/js_command_match/delete_key.rs
- src/js_command_match/deploy.rs
- src/js_command_match/dev_deploy.rs
- src/js_command_match/evm_call.rs
- src/js_command_match/evm_dev_init.rs
- src/js_command_match/evm_view.rs
- src/js_command_match/generate_key.rs
- src/js_command_match/js.rs
- src/js_command_match/keys.rs
- src/js_command_match/login.rs
- src/js_command_match/mod.rs
- src/js_command_match/proposals.rs
- src/js_command_match/repl.rs
- src/js_command_match/send.rs
- src/js_command_match/set_api_key.rs
- src/js_command_match/stake.rs
- src/js_command_match/state.rs
- src/js_command_match/tx_status.rs
- src/js_command_match/validators.rs
- src/js_command_match/view.rs
- src/js_command_match/view_state.rs
- src/main.rs
> Implement compatibility layer for near-cli (JS)

- src/common.rs
> Display access key list

- Cargo.lock
- Cargo.toml
- docs/GUIDE.en.md
- docs/GUIDE.ru.md
- src/commands/account/create_account/fund_myself_create_account/add_key/autogenerate_new_keypair/mod.rs
- src/commands/account/create_account/fund_myself_create_account/add_key/mod.rs
- src/commands/account/create_account/fund_myself_create_account/add_key/use_ledger/mod.rs
- src/commands/account/create_account/fund_myself_create_account/add_key/use_manually_provided_seed_phrase/mod.rs
- src/commands/account/create_account/fund_myself_create_account/add_key/use_public_key/mod.rs
- src/commands/account/create_account/fund_myself_create_account/mod.rs
- src/commands/account/create_account/fund_myself_create_account/sign_as/mod.rs
- src/commands/account/create_account/mod.rs
- src/commands/account/create_account/sponsor_by_faucet_service/add_key/autogenerate_new_keypair/mod.rs
- src/commands/account/create_account/sponsor_by_faucet_service/add_key/mod.rs
- src/commands/account/create_account/sponsor_by_faucet_service/add_key/use_ledger/mod.rs
- src/commands/account/create_account/sponsor_by_faucet_service/add_key/use_manually_provided_seed_phrase/mod.rs
- src/commands/account/create_account/sponsor_by_faucet_service/add_key/use_public_key/mod.rs
- src/commands/account/create_account/sponsor_by_faucet_service/mod.rs
- src/commands/account/create_account/sponsor_by_faucet_service/network/mod.rs
- src/commands/config/add_connection/mod.rs
- src/common.rs
- src/config.rs
- src/types/account_id.rs
> Create account with sponsor by faucet service

- src/commands/contract/call_function/as_read_only/mod.rs
- src/commands/contract/call_function/as_transaction/mod.rs
- src/common.rs
> Show function call logs

- Cargo.lock
- Cargo.toml
- src/commands/account/list_keys/mod.rs
- src/commands/account/view_account_summary/mod.rs
- src/common.rs
- src/main.rs
Changed output of view-account-summary method using prettytable-rs
> feat: improved account view-account-summary method

- src/commands/account/create_account/fund_myself_create_account/mod.rs
- src/commands/account/create_account/fund_myself_create_account/sign_as/mod.rs
- src/common.rs
- src/transaction_signature_options/sign_with_access_key_file/mod.rs
- src/transaction_signature_options/sign_with_keychain/mod.rs
- src/transaction_signature_options/sign_with_ledger/mod.rs
- src/transaction_signature_options/sign_with_macos_keychain/mod.rs
- src/transaction_signature_options/sign_with_private_key/mod.rs
- src/transaction_signature_options/sign_with_seed_phrase/mod.rs
> feat: Use optimisticly latest nonce for the access key instead of the final one to avoid errors running commands one after the other

- src/commands/account/add_key/autogenerate_new_keypair/print_keypair_to_terminal/mod.rs
- src/commands/account/add_key/autogenerate_new_keypair/save_keypair_to_keychain/mod.rs
- src/commands/account/add_key/autogenerate_new_keypair/save_keypair_to_macos_keychain/mod.rs
- src/commands/account/add_key/use_manually_provided_seed_phrase/mod.rs
- src/commands/account/add_key/use_public_key/mod.rs
- src/commands/account/create_account/fund_myself_create_account/sign_as/mod.rs
- src/commands/account/delete_account/mod.rs
- src/commands/account/delete_key/mod.rs
- src/commands/account/mod.rs
- src/commands/account/storage_management/mod.rs
- src/commands/account/storage_management/storage_deposit.rs
- src/commands/account/storage_management/storage_withdraw.rs
- src/commands/account/storage_management/view_storage_balance.rs
- src/commands/contract/call_function/as_transaction/mod.rs
- src/commands/contract/deploy/initialize_mode/call_function_type/mod.rs
- src/commands/contract/deploy/initialize_mode/mod.rs
- src/commands/mod.rs
- src/commands/tokens/send_ft/mod.rs
- src/commands/tokens/send_near/mod.rs
- src/commands/tokens/send_nft/mod.rs
- src/commands/transaction/construct_transaction/skip_action/mod.rs
- src/common.rs
- src/network_for_transaction/mod.rs
- src/transaction_signature_options/sign_with_access_key_file/mod.rs
- src/transaction_signature_options/sign_with_keychain/mod.rs
- src/transaction_signature_options/sign_with_ledger/mod.rs
- src/transaction_signature_options/sign_with_macos_keychain/mod.rs
- src/transaction_signature_options/sign_with_private_key/mod.rs
- src/transaction_signature_options/sign_with_seed_phrase/mod.rs
https://nomicon.io/Standards/StorageManagement
> Storage management

- .github/workflows/release-plz.yml
solves https://github.com/MarcoIeni/release-plz/issues/706
> fix: pass right token to release-plz action

- src/commands/account/add_key/mod.rs
- src/commands/account/add_key/use_ledger/mod.rs
Added support for adding key from Ledger hardware wallet which was requested in [this](https://github.com/near/near-cli-rs/issues/163) issue.
> Support for adding key from Ledger hardware wallet

- Cargo.lock
- Cargo.toml
- src/commands/tokens/send_near/mod.rs
- src/commands/transaction/mod.rs
- src/commands/transaction/send_signed_transaction/mod.rs
- src/commands/transaction/send_signed_transaction/network/mod.rs
> Send signed transaction

- Cargo.lock
- Cargo.toml
- src/commands/contract/download_wasm/mod.rs
- src/commands/extensions/self_update/mod.rs
- src/commands/tokens/send_ft/mod.rs
- src/commands/transaction/sign_transaction/mod.rs
- src/commands/transaction/view_status/mod.rs
> fix: self update

- src/js_command_match/call.rs
> fix: Near Call Command

- src/commands/account/create_account/sponsor_by_faucet_service/mod.rs
Resolves https://github.com/near/near-cli-rs/issues/242
> chore: propagate faucet error message

- src/transaction_signature_options/sign_with_ledger/mod.rs
was tested with `near --offline transaction sign-transaction ...` : https://nearblocks.io/txns/5TAhPcpGAPLVs4R5ZANYPaUxdw1PviyqsizFnHpaDhK7
> feat: add `--offline` for `sign-with-ledger` option

- src/commands/account/delete_key/mod.rs
- src/commands/account/delete_key/public_keys_to_delete.rs
- src/commands/account/mod.rs
- src/types/public_key_list.rs
- src/types/vec_string.rs
> feat: Added the ability to select access keys to remove from the list of public keys

- src/commands/extensions/self_update/mod.rs
> feat: Improved self-update UX with more details

- src/commands/account/add_key/access_key_type/mod.rs
- src/commands/account/create_account/fund_myself_create_account/mod.rs
- src/commands/account/storage_management/storage_deposit.rs
- src/commands/account/storage_management/storage_withdraw.rs
- src/commands/contract/call_function/as_transaction/mod.rs
- src/commands/contract/deploy/initialize_mode/call_function_type/mod.rs
- src/commands/staking/delegate/deposit_and_stake.rs
- src/commands/staking/delegate/stake.rs
- src/commands/staking/delegate/unstake.rs
- src/commands/staking/delegate/withdraw.rs
- src/commands/tokens/send_ft/mod.rs
- src/commands/tokens/send_near/mod.rs
- src/commands/tokens/send_nft/mod.rs
- src/commands/tokens/view_ft_balance/mod.rs
- src/commands/transaction/construct_transaction/add_action_1/add_action/add_key/access_key_type/mod.rs
- src/commands/transaction/construct_transaction/add_action_1/add_action/call_function/mod.rs
- src/commands/transaction/construct_transaction/add_action_1/add_action/stake/mod.rs
- src/commands/transaction/construct_transaction/add_action_1/add_action/transfer/mod.rs
- src/commands/transaction/construct_transaction/add_action_2/add_action/add_key/access_key_type/mod.rs
- src/commands/transaction/construct_transaction/add_action_2/add_action/call_function/mod.rs
- src/commands/transaction/construct_transaction/add_action_2/add_action/stake/mod.rs
- src/commands/transaction/construct_transaction/add_action_2/add_action/transfer/mod.rs
- src/commands/transaction/construct_transaction/add_action_3/add_action/add_key/access_key_type/mod.rs
- src/commands/transaction/construct_transaction/add_action_3/add_action/call_function/mod.rs
- src/commands/transaction/construct_transaction/add_action_3/add_action/stake/mod.rs
- src/commands/transaction/construct_transaction/add_action_3/add_action/transfer/mod.rs
- src/commands/transaction/reconstruct_transaction/mod.rs
- src/common.rs
- src/types/mod.rs
- src/types/near_token.rs
Incorrect representation of the NEAR token.
After correction:
> Fix: NEAR token representation

- docs/GUIDE.en.md
- docs/GUIDE.ru.md
- src/commands/transaction/reconstruct_transaction/mod.rs
Updated:
- GUIDE
- entering the network name
> refactor: Updated reconstruct-transaction command

- src/commands/contract/call_function/as_read_only/mod.rs
- src/commands/contract/call_function/as_transaction/mod.rs
- src/commands/contract/call_function/call_function_args_type/mod.rs
- src/commands/contract/deploy/initialize_mode/call_function_type/mod.rs
- src/commands/transaction/construct_transaction/add_action_1/add_action/call_function/mod.rs
- src/commands/transaction/construct_transaction/add_action_2/add_action/call_function/mod.rs
- src/commands/transaction/construct_transaction/add_action_3/add_action/call_function/mod.rs
> feat: Updated dialog for entering arguments to a function (as-read-only)

- docs/GUIDE.en.md
- src/commands/account/add_key/mod.rs
> chore: fix typos

- src/types/vec_string.rs
> fix: Wrong console command for adding Function-Call key with any methods to account

- src/commands/account/add_key/use_ledger/mod.rs
- src/commands/account/create_account/create_implicit_account/use_ledger.rs
- src/commands/account/create_account/fund_myself_create_account/add_key/use_ledger/mod.rs
- src/commands/account/create_account/sponsor_by_faucet_service/add_key/use_ledger/mod.rs
- src/transaction_signature_options/sign_with_ledger/mod.rs
> feat: Added the ability to select HD Path from the ledger

- src/commands/account/delete_key/public_keys_to_delete.rs
Resolves #383 
If no access key is entered:
> fix: The process of removing access keys has been fixed

- Cargo.lock
- Cargo.toml
- src/common.rs
> chore!: updates near-* dependencies to 0.27 release

- src/lib.rs
- src/main.rs
Created a setup_tracing() function in the library. It provides tracing configuration for loading wait indicators and the --teach-me flag.
> feat: Trace configuration for loading wait indicators and --teach-me flag moved to library

- Cargo.lock
- Cargo.toml
- src/commands/transaction/reconstruct_transaction/mod.rs
- src/common.rs
- src/transaction_signature_options/mod.rs
Updated dependencies for the new version.
This PR is going hand-by-hand with #456 and #457 (Splitted to simplify reviewing process)
> chore!: updates near-* dependencies to 0.29 release

- .github/workflows/code_style.yml
- .github/workflows/release.yml
- Cargo.toml
Linux arm64 hosting runners are now available for free in public GitHub repositories
> feat: Use free ARM64 GitHub Action runners for pre-built binaries

- src/commands/tokens/send_ft/amount_ft.rs
- src/commands/tokens/send_ft/mod.rs
@race-of-sloths include it, please
It works as expected:
> refactor: Refactored 'send-ft memo' command from using Option<String> to just String

- src/commands/account/create_account/fund_myself_create_account/mod.rs
- src/commands/account/create_account/fund_myself_create_account/sign_as/mod.rs
- src/commands/account/delete_account/mod.rs
- src/commands/account/import_account/mod.rs
- src/commands/account/storage_management/storage_deposit.rs
- src/commands/account/update_social_profile/sign_as.rs
- src/commands/contract/call_function/mod.rs
- src/commands/tokens/send_ft/amount_ft.rs
- src/commands/transaction/construct_transaction/add_action_1/add_action/delete_account/mod.rs
- src/commands/transaction/construct_transaction/add_action_2/add_action/delete_account/mod.rs
- src/commands/transaction/construct_transaction/add_action_3/add_action/delete_account/mod.rs
- src/commands/transaction/send_meta_transaction/sign_as/mod.rs
- src/common.rs
> fix: Fixed canceling the CLI operation

- Cargo.lock
- Cargo.toml
- src/commands/contract/deploy_global/mod.rs
- src/common.rs
> chore!: updates near-* dependencies to 0.30 release

- src/commands/contract/call_function/as_read_only/mod.rs
- src/common.rs
> fix: Fixed returning the result of a function call

- src/common.rs
> feat: display global contracts info on account details query

- docs/SHELL_HISTORY_INTEGRATION.md
- src/common.rs
- src/transaction_signature_options/sign_with_ledger/mod.rs
> chore: fix some typos
